# Refer to https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest


stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - echo "Start to build..."
    - go vet $(go list ./... | grep -v /someframes)
    - go build gofly/algodemos gofly/ctrlsys gofly/stdlibdemo

test-job1:
  stage: test
  script:
    - echo "Run all the tests"
    # go test -v -timeout 30s gofly/algodemos
    - go test -v -timeout 30s -race $(go list ./... | grep -v /vendor/)
