name: Go package

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        # go mod tidy?
        run: |
          go get .

      - name: Build
        run: |
          echo "Start to verify build..."
          go vet $(go list ./... | grep -v /vendor/)
          go build gofly/algodemos gofly/stdlibdemo

      - name: Test
        run: go test -v ./...